Web Server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -10,5 +10,12 @@ file_path=$1
 ip_adress=$2
 username=$3
 path_t_ssh_key=$4
-disabbling the strict hostkey checking
+#disabbling the strict hostkey checking
 scp -o "StrictHostKeyChecking" -i "$path_to_ssh_key" "$file_path" "$username@$ip_adress:~"
+#Confirming if the transfer is successful
+if [$? eq 0]
+then
+        echo "File transfer was successful"
+else
+        echo "File transfer failed"
+fi
